- id: '1530087408395'
  alias: Travel time - Jena Erfurt
  trigger:
  - at: '10:23:30'
    platform: time
  condition: []
  action:
  - data:
      message: 'Current travel time from Jena to Erfurt: {{ states.sensor.travel_jena_erfurt.attributes.duration_in_traffic
        }}'
    service: notify.telegramtest
